# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy Simple HTML to Azure Web App - my-simple-react-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy: # Змінено назву завдання
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout
      id-token: write # This is required for requesting the JWT

    steps:
      - uses: actions/checkout@v4

      # Для простого HTML-сайту, нам не потрібні npm, Node.js або React-збірка.
      # Ми просто пакуємо наш index.html.

      - name: Zip HTML for deployment
        run: zip release.zip index.html # Пакуємо лише index.html

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: html-app # Змінено назву артефакту
          path: release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_69C94AB1049C4399889B4A06EC627FD5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_64AD1C9AC67849539EFBD36A1DE073D8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E2C3A315157B4C78B574DC5EAF8E6277 }}

      - name: Download artifact for deployment
        uses: actions/download-artifact@v4
        with:
          name: html-app # Завантажуємо артефакт з правильною назвою

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'my-simple-react-app' # Переконайтесь, що це ім'я вашого App Service
          slot-name: 'Production'
          package: . # Розгортаємо весь вміст ZIP-файлу (тепер це index.html)
